services:
  mongodb:
    image: 'mongo:latest'
    restart: unless-stopped
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MONGO_INITDB_DATABASE=${DB_NAME}'
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local