services:
  mongodb:
    image: 'mongo:latest'
    restart: unless-stopped
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=test'
      - 'MONGO_INITDB_ROOT_PASSWORD=202cb962ac59075b964b07152d234b70'
      - 'MONGO_INITDB_DATABASE=plazoleta-trazabilidad'
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local