server:
  port: ${PORT}

spring:
  data:
    mongodb:
      database: ${DB_NAME}
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: admin
      authentication-mechanism: SCRAM-SHA-256

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_TIME}

appDescription: "Plazoleta Trazabilidad"
appVersion: "1.0.0"
