server:
  port: 8083

spring:
  data:
    mongodb:
      database: plazoleta-trazabilidad
      host: localhost
      port: 27017
      username: test
      password: test

jwt:
  secret: 123456
  expiration: 1

appDescription: "Plazoleta Trazabilidad"
appVersion: "1.0.0"
